# Generated by Django 3.2.7 on 2021-09-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='dp',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
